[package]
name = "lumepeer-decoder-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true

[[bin]]
name = "lumepeer-decoder-worker"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
lumepeer-media.workspace = true
openh264.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(all(target_os = "linux", not(target_os = "android")))'.dependencies]
seccompiler.workspace = true
libc.workspace = true
