//! `/v1/license/*` (design doc §12.2).
//!
//! Issue is idempotent per `idempotency_key`; heartbeat only records liveness
//! and never ends an active session on its own — a missed heartbeat is part of
//! the offline grace of §12.4, not a separate failure mode.

use axum::extract::State;
use axum::http::StatusCode;
use axum::routing::post;
use axum::{Json, Router};
use serde::{Deserialize, Serialize};

use crate::AppState;

/// Mounts the license routes.
pub fn router() -> Router<AppState> {
    Router::new()
        .route("/v1/license/issue", post(issue))
        .route("/v1/license/heartbeat", post(heartbeat))
        .route("/v1/license/revoke", post(revoke))
        .route("/v1/license/refresh", post(refresh))
}

/// Body of `/v1/license/issue`.
#[derive(Debug, Deserialize)]
pub struct IssueRequest {
    /// Account the license belongs to.
    pub account_id: String,
    /// Random device identifier generated by the client (§7).
    pub device_id: String,
    /// Retrying with the same key returns the previously issued token (§12.2).
    pub idempotency_key: String,
}

/// Response carrying a signed license token (§12.1).
#[derive(Debug, Serialize)]
pub struct TokenResponse {
    /// Base64 of the binary token.
    pub token: String,
}

/// Body of `/v1/license/heartbeat`.
#[derive(Debug, Deserialize)]
pub struct HeartbeatRequest {
    /// Device reporting in, every `HEARTBEAT_INTERVAL_SECS` (§12.2).
    pub device_id: String,
    /// Cumulative active session seconds, checked against the trial limit (§12.3).
    pub active_seconds: u64,
}

async fn issue(
    State(_state): State<AppState>,
    Json(_body): Json<IssueRequest>,
) -> (StatusCode, &'static str) {
    (StatusCode::NOT_IMPLEMENTED, "phase 3: license issue")
}

async fn heartbeat(
    State(_state): State<AppState>,
    Json(_body): Json<HeartbeatRequest>,
) -> (StatusCode, &'static str) {
    (StatusCode::NOT_IMPLEMENTED, "phase 3: license heartbeat")
}

async fn revoke(State(_state): State<AppState>) -> (StatusCode, &'static str) {
    (StatusCode::NOT_IMPLEMENTED, "phase 3: license revoke")
}

async fn refresh(State(_state): State<AppState>) -> (StatusCode, &'static str) {
    (StatusCode::NOT_IMPLEMENTED, "phase 3: license refresh")
}
