//! Control protocol wire types (design doc §9.1).
//!
//! Serialization is `postcard`; framing (`u32_be length || payload`) lives in
//! `lumepeer-net::framing`, which enforces the length check before allocating.

use serde::{Deserialize, Serialize};

use crate::consent::Role;
use crate::constants::MAX_CONTROL_FRAME_BYTES;
use crate::error::{CoreError, Result};

/// Logical identifiers at or above this value denote pointer buttons rather
/// than keys.
///
/// §9.1 fixes the field but not the namespace; splitting it here lets the host
/// policy of §8.2 distinguish `PointerClick` from `KeyPress` without a platform
/// scancode table. See docs/adr/0007.
pub const POINTER_BUTTON_LOGICAL_BASE: u32 = 0xF000_0000;

/// Protocol major version. A mismatch closes the connection before consent (§9.1).
pub const PROTOCOL_MAJOR: u16 = 1;
/// Protocol minor version. Unknown optional features are ignored (§9.1).
pub const PROTOCOL_MINOR: u16 = 0;

/// Direction of a control message, part of the anti-replay tuple (§9.1).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Direction {
    /// Host to guest.
    HostToGuest,
    /// Guest to host.
    GuestToHost,
}

/// Envelope carried by every control frame (§9.1).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MessageEnvelope {
    /// Session identifier generated by the host via CSPRNG after handshake.
    pub session_id: [u8; 16],
    /// Direction of this message.
    pub direction: Direction,
    /// Strictly monotonic per `(session_id, direction)`, starts at 0.
    pub seq: u64,
    /// Message discriminant.
    pub kind: MessageKind,
    /// Opaque body, at most `MAX_CONTROL_FRAME_BYTES`.
    pub body: Vec<u8>,
}

/// Control message kinds (§9.1).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum MessageKind {
    /// First message of a connection, carries the invite proof.
    Hello {
        /// Protocol major of the sender.
        major: u16,
        /// Protocol minor of the sender.
        minor: u16,
        /// Role the guest asks for; the host still decides (§2.3).
        role_request: Role,
        /// Optional feature strings; unknown ones are ignored.
        features: Vec<String>,
        /// Proof of possession of a valid invite (§7).
        invite_proof: Vec<u8>,
    },
    /// Answer to `Hello`.
    HelloAck {
        /// Protocol major of the responder.
        major: u16,
        /// Protocol minor of the responder.
        minor: u16,
    },
    /// Guest asks the host user for consent.
    ConsentRequest,
    /// Host grants the given role.
    ConsentGrant(Role),
    /// Host revokes all grants.
    ConsentRevoke,
    /// Media session may start.
    SessionStart,
    /// Media session must stop.
    SessionStop,
    /// License expiry warning (§12).
    LicenseWarn {
        /// Seconds left in the current license window.
        seconds_left: u64,
    },
    /// License check failed; session must end (§12.4).
    LicenseDeny {
        /// Reason, free of secrets (§15).
        reason: String,
    },
    /// Input event from guest to host.
    InputEvent(InputEventPayload),
    /// Clipboard payload, text/plain UTF-8 only (§9.2).
    ClipboardSync {
        /// Clipboard bytes, at most `CLIPBOARD_MAX_BYTES`.
        data: Vec<u8>,
    },
    /// Guest asks to record the session.
    RecordRequest,
    /// Host answer to `RecordRequest`.
    RecordAck(bool),
    /// Offer of a single file (§9.2).
    FileOffer {
        /// Basename after normalization, no path separators.
        name: String,
        /// File size, at most `FILE_OFFER_MAX_BYTES`.
        size: u64,
        /// BLAKE3 of the whole file, verified before export from staging.
        hash: [u8; 32],
    },
    /// Answer to `FileOffer`; `true` opens the `rd/file/1` connection (§4).
    FileAccept(bool),
    /// Encoder target adjustment derived from receiver feedback (§11).
    QualityAdjust {
        /// Requested frame rate.
        target_fps: u8,
        /// Requested bitrate.
        target_bitrate_kbps: u32,
    },
    /// Keepalive, sent every `PING_INTERVAL_SECS` (§9.1).
    Ping(u64),
    /// Answer to `Ping`.
    Pong(u64),
    /// Resume attempt inside the reconnect window (§10).
    ResumeHello {
        /// Session being resumed.
        session_id: [u8; 16],
        /// Highest sequence number the sender has processed.
        last_received_seq: u64,
    },
}

/// Input event payload: logical key plus physical scancode, never raw OS
/// handles (§11).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InputEventPayload {
    /// Platform-independent logical key or button identifier.
    pub logical: u32,
    /// Physical scancode as reported by the guest.
    pub scancode: u32,
    /// Modifier bitmask.
    pub modifiers: u32,
    /// Event-specific data (pointer coordinates, wheel delta, press/release).
    pub detail: InputDetail,
}

/// Discriminates the kind of input carried by an [`InputEventPayload`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum InputDetail {
    /// Key or button press.
    Press,
    /// Key or button release.
    Release,
    /// Absolute pointer motion, normalized to the captured surface.
    PointerMove {
        /// Horizontal position in 0..=65535 of the captured surface width.
        x: u16,
        /// Vertical position in 0..=65535 of the captured surface height.
        y: u16,
    },
    /// Scroll wheel movement.
    Wheel {
        /// Horizontal delta.
        dx: i16,
        /// Vertical delta.
        dy: i16,
    },
}

impl MessageEnvelope {
    /// Serializes the envelope.
    ///
    /// # Errors
    /// Returns [`CoreError::FrameSize`] if the encoding exceeds
    /// `MAX_CONTROL_FRAME_BYTES`, and [`CoreError::Malformed`] if `postcard`
    /// cannot encode the value.
    pub fn encode(&self) -> Result<Vec<u8>> {
        let bytes = postcard::to_allocvec(self).map_err(|_| CoreError::Malformed)?;
        if bytes.is_empty() || bytes.len() > MAX_CONTROL_FRAME_BYTES {
            return Err(CoreError::FrameSize { size: bytes.len() });
        }
        Ok(bytes)
    }

    /// Deserializes an envelope from an already length-checked frame.
    ///
    /// # Errors
    /// Returns [`CoreError::FrameSize`] if `bytes` is empty or longer than
    /// `MAX_CONTROL_FRAME_BYTES`, and [`CoreError::Malformed`] on any decoding
    /// failure. The size check happens before `postcard` touches the input
    /// (§9.1: allocation-DoS protection).
    pub fn decode(bytes: &[u8]) -> Result<Self> {
        if bytes.is_empty() || bytes.len() > MAX_CONTROL_FRAME_BYTES {
            return Err(CoreError::FrameSize { size: bytes.len() });
        }
        // `postcard::from_bytes` stops at the end of the value and ignores
        // whatever follows. A frame is length-prefixed, so trailing bytes mean
        // the two sides disagree about what the frame contains; that is a
        // malformed frame, not a decodable one with padding. Rejecting it also
        // keeps the encoding canonical, which the interop vectors of §17.2 rely
        // on.
        let (envelope, rest) =
            postcard::take_from_bytes::<Self>(bytes).map_err(|_| CoreError::Malformed)?;
        if !rest.is_empty() {
            return Err(CoreError::Malformed);
        }
        Ok(envelope)
    }
}

/// Checks that `remote_major` matches [`PROTOCOL_MAJOR`].
///
/// # Errors
/// Returns [`CoreError::IncompatibleVersion`] on mismatch; the caller closes
/// the connection before any consent decision (§9.1, §18).
pub const fn check_version(remote_major: u16) -> Result<()> {
    if remote_major == PROTOCOL_MAJOR {
        Ok(())
    } else {
        Err(CoreError::IncompatibleVersion {
            local: PROTOCOL_MAJOR,
            remote: remote_major,
        })
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;

    fn envelope(kind: MessageKind) -> MessageEnvelope {
        MessageEnvelope {
            session_id: [7u8; 16],
            direction: Direction::GuestToHost,
            seq: 0,
            kind,
            body: Vec::new(),
        }
    }

    #[test]
    fn roundtrip_preserves_envelope() {
        let original = envelope(MessageKind::ConsentGrant(Role::ViewOnly));
        let bytes = original.encode().unwrap();
        assert_eq!(MessageEnvelope::decode(&bytes).unwrap(), original);
    }

    #[test]
    fn empty_frame_is_rejected() {
        assert!(matches!(
            MessageEnvelope::decode(&[]),
            Err(CoreError::FrameSize { size: 0 })
        ));
    }

    #[test]
    fn trailing_bytes_make_a_frame_malformed() {
        let envelope = MessageEnvelope {
            session_id: [1u8; 16],
            direction: Direction::HostToGuest,
            seq: 0,
            kind: MessageKind::ConsentRevoke,
            body: Vec::new(),
        };
        let mut bytes = envelope.encode().unwrap();
        assert_eq!(MessageEnvelope::decode(&bytes).unwrap(), envelope);
        bytes.push(0xff);
        assert!(matches!(
            MessageEnvelope::decode(&bytes),
            Err(CoreError::Malformed)
        ));
    }

    #[test]
    fn oversized_frame_is_rejected_before_decoding() {
        let oversized = vec![0u8; MAX_CONTROL_FRAME_BYTES + 1];
        assert!(matches!(
            MessageEnvelope::decode(&oversized),
            Err(CoreError::FrameSize { .. })
        ));
    }

    #[test]
    fn major_mismatch_is_incompatible() {
        assert!(check_version(PROTOCOL_MAJOR).is_ok());
        assert!(matches!(
            check_version(PROTOCOL_MAJOR + 1),
            Err(CoreError::IncompatibleVersion { .. })
        ));
    }
}
