//! Control protocol wire types (design doc §9.1).
//!
//! Serialization is `postcard`; framing (`u32_be length || payload`) lives in
//! `lumepeer-net::framing`, which enforces the length check before allocating.

use serde::{Deserialize, Serialize};

use crate::consent::Role;
use crate::constants::{
    CHAT_MAX_BYTES, CLIPBOARD_MAX_BYTES, FILE_OFFER_MAX_BYTES, MAX_CONTROL_FRAME_BYTES,
    MAX_CURSOR_SHAPE_PIXELS, MAX_MONITORS_PER_HOST,
};
use crate::error::{CoreError, Result};

/// Logical identifiers at or above this value denote pointer buttons rather
/// than keys.
///
/// §9.1 fixes the field but not the namespace; splitting it here lets the host
/// policy of §8.2 distinguish `PointerClick` from `KeyPress` without a platform
/// scancode table. See docs/adr/0007.
pub const POINTER_BUTTON_LOGICAL_BASE: u32 = 0xF000_0000;

/// `Shift` bit of [`InputEventPayload::modifiers`].
///
/// §9.1 fixes the field but not its bit layout, the same gap `POINTER_BUTTON_
/// LOGICAL_BASE` fills for `logical`. The guest webview's `modifiersOf`
/// (`apps/desktop/src/view-window.ts`) writes exactly these four bits, and the
/// platform injectors of §11 read them back — the X11 one has to, since it
/// needs to know whether the character it was asked for is reachable at the
/// current shift level of the host's own layout.
pub const MODIFIER_SHIFT: u32 = 1 << 0;
/// `Control` bit of [`InputEventPayload::modifiers`].
pub const MODIFIER_CTRL: u32 = 1 << 1;
/// `Alt` bit of [`InputEventPayload::modifiers`].
pub const MODIFIER_ALT: u32 = 1 << 2;
/// `Meta`/`Super`/`Command` bit of [`InputEventPayload::modifiers`].
pub const MODIFIER_META: u32 = 1 << 3;

/// Protocol major version. A mismatch closes the connection before consent (§9.1).
pub const PROTOCOL_MAJOR: u16 = 1;
/// Protocol minor version. Unknown optional features are ignored (§9.1).
///
/// 1: appended `Chat`, `KeyframeRequest`, `CursorShape`, `MonitorsList`,
/// `MonitorSelect`, `PrivacyMode`/`PrivacyModeAck`, `AudioStart`/`AudioStop`,
/// `FileAbort` and `FileChunkAck` after `ResumeHello`; added per-message
/// limit checks in `MessageEnvelope::decode`. Existing variants kept their
/// discriminants, so a MINOR 0 peer decodes every old message unchanged.
pub const PROTOCOL_MINOR: u16 = 1;

/// Direction of a control message, part of the anti-replay tuple (§9.1).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Direction {
    /// Host to guest.
    HostToGuest,
    /// Guest to host.
    GuestToHost,
}

/// Envelope carried by every control frame (§9.1).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MessageEnvelope {
    /// Session identifier generated by the host via CSPRNG after handshake.
    pub session_id: [u8; 16],
    /// Direction of this message.
    pub direction: Direction,
    /// Strictly monotonic per `(session_id, direction)`, starts at 0.
    pub seq: u64,
    /// Message discriminant.
    pub kind: MessageKind,
    /// Opaque body, at most `MAX_CONTROL_FRAME_BYTES`.
    pub body: Vec<u8>,
}

/// Control message kinds (§9.1).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum MessageKind {
    /// First message of a connection, carries the invite proof.
    Hello {
        /// Protocol major of the sender.
        major: u16,
        /// Protocol minor of the sender.
        minor: u16,
        /// Role the guest asks for; the host still decides (§2.3).
        role_request: Role,
        /// Optional feature strings; unknown ones are ignored.
        features: Vec<String>,
        /// Proof of possession of a valid invite (§7).
        invite_proof: Vec<u8>,
    },
    /// Answer to `Hello`.
    HelloAck {
        /// Protocol major of the responder.
        major: u16,
        /// Protocol minor of the responder.
        minor: u16,
    },
    /// Guest asks the host user for consent.
    ConsentRequest,
    /// Host grants the given role.
    ConsentGrant(Role),
    /// Host revokes all grants.
    ConsentRevoke,
    /// Media session may start.
    SessionStart,
    /// Media session must stop.
    SessionStop,
    /// License expiry warning (§12).
    LicenseWarn {
        /// Seconds left in the current license window.
        seconds_left: u64,
    },
    /// License check failed; session must end (§12.4).
    LicenseDeny {
        /// Reason, free of secrets (§15).
        reason: String,
    },
    /// Input event from guest to host.
    InputEvent(InputEventPayload),
    /// Clipboard payload, text/plain UTF-8 only (§9.2).
    ClipboardSync {
        /// Clipboard bytes, at most `CLIPBOARD_MAX_BYTES`.
        data: Vec<u8>,
    },
    /// Guest asks to record the session.
    RecordRequest,
    /// Host answer to `RecordRequest`.
    RecordAck(bool),
    /// Offer of a single file (§9.2).
    FileOffer {
        /// Basename after normalization, no path separators.
        name: String,
        /// File size, at most `FILE_OFFER_MAX_BYTES`.
        size: u64,
        /// BLAKE3 of the whole file, verified before export from staging.
        hash: [u8; 32],
    },
    /// Answer to `FileOffer`; `true` opens the `rd/file/1` connection (§4).
    FileAccept(bool),
    /// Encoder target adjustment derived from receiver feedback (§11).
    QualityAdjust {
        /// Requested frame rate.
        target_fps: u8,
        /// Requested bitrate.
        target_bitrate_kbps: u32,
    },
    /// Keepalive, sent every `PING_INTERVAL_SECS` (§9.1).
    Ping(u64),
    /// Answer to `Ping`.
    Pong(u64),
    /// Resume attempt inside the reconnect window (§10).
    ResumeHello {
        /// Session being resumed.
        session_id: [u8; 16],
        /// Highest sequence number the sender has processed.
        last_received_seq: u64,
    },
    /// One chat message of the in-session text chat (§9.2).
    ///
    /// Appended after `ResumeHello` so every earlier variant keeps its
    /// postcard discriminant; the golden vectors of §17.2 depend on that
    /// (`PROTOCOL_MINOR 1`).
    Chat {
        /// UTF-8 message, at most `CHAT_MAX_BYTES` bytes.
        text: String,
    },
    /// Guest asks the host encoder for an instant keyframe (§11): decoder
    /// joined mid-stream or packets were lost beyond what the jitter buffer
    /// can conceal. The host must answer with a keyframe at the next
    /// opportunity, rate-limited by the caller.
    KeyframeRequest,
    /// Host announces the shape of its cursor (§11). Sent when the cursor
    /// changes; the guest draws it locally over the video for minimum input
    /// latency feedback.
    CursorShape {
        /// Shape payload: geometry plus RGBA pixels.
        shape: CursorShapeData,
    },
    /// Host lists the monitors a guest may target (§11).
    MonitorsList {
        /// One entry per monitor, at most `MAX_MONITORS_PER_HOST`.
        monitors: Vec<MonitorInfo>,
    },
    /// Guest picks which monitor to capture; the host re-targets capture.
    MonitorSelect {
        /// Monitor id as announced in `MonitorsList`.
        monitor_id: u32,
    },
    /// Guest asks the host to enable or disable privacy mode (§11): blank
    /// the host's physical monitors and block local input while the session
    /// is controlled. The host user must have enabled this capability.
    PrivacyMode {
        /// `true` to blank and lock, `false` to restore.
        enabled: bool,
    },
    /// Host answers `PrivacyMode`: whether the mode actually became active.
    PrivacyModeAck {
        /// Whether privacy mode is now active on the host.
        active: bool,
    },
    /// Host offers to start streaming audio (§11); parameters are fixed by
    /// constants (`AUDIO_SAMPLE_RATE_HZ` etc.) so none travel on the wire.
    AudioStart {
        /// Sample rate, always `AUDIO_SAMPLE_RATE_HZ` today.
        sample_rate_hz: u32,
        /// Channel count, always `AUDIO_CHANNELS` today.
        channels: u8,
    },
    /// Either side stops the audio channel (§11).
    AudioStop,
    /// Sender aborts one file transfer mid-flight (§9.2). Unlike
    /// `FileAccept(false)` this applies after chunking has already begun.
    FileAbort {
        /// Transfer being aborted, as announced in `FileTransferStart`.
        transfer_id: u64,
    },
    /// Receiver acknowledges contiguous bytes received (§9.2), driving the
    /// sender's resume point after a reconnect.
    FileChunkAck {
        /// Transfer being acknowledged.
        transfer_id: u64,
        /// Number of leading bytes now durably received.
        offset: u64,
    },
}

/// Pixel geometry plus RGBA payload of one cursor shape (§11).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CursorShapeData {
    /// Width in pixels, at least 1.
    pub width: u16,
    /// Height in pixels, at least 1.
    pub height: u16,
    /// Hotspot x within the shape.
    pub hotspot_x: u16,
    /// Hotspot y within the shape.
    pub hotspot_y: u16,
    /// Premultiplied BGRA pixels, exactly `width * height * 4` bytes and at
    /// most `MAX_CURSOR_SHAPE_PIXELS * 4`.
    pub rgba: Vec<u8>,
}

/// One monitor of the host, as reported in `MonitorsList` (§11).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct MonitorInfo {
    /// Host-assigned stable id a guest passes back in `MonitorSelect`.
    pub id: u32,
    /// Width in pixels.
    pub width: u32,
    /// Height in pixels.
    pub height: u32,
    /// Whether this is the host's primary display.
    pub primary: bool,
}

/// Input event payload: logical key plus physical scancode, never raw OS
/// handles (§11).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InputEventPayload {
    /// Platform-independent logical key or button identifier.
    pub logical: u32,
    /// Physical scancode as reported by the guest.
    pub scancode: u32,
    /// Modifier bitmask.
    pub modifiers: u32,
    /// Event-specific data (pointer coordinates, wheel delta, press/release).
    pub detail: InputDetail,
}

/// Discriminates the kind of input carried by an [`InputEventPayload`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum InputDetail {
    /// Key or button press.
    Press,
    /// Key or button release.
    Release,
    /// Absolute pointer motion, normalized to the captured surface.
    PointerMove {
        /// Horizontal position in 0..=65535 of the captured surface width.
        x: u16,
        /// Vertical position in 0..=65535 of the captured surface height.
        y: u16,
    },
    /// Scroll wheel movement.
    Wheel {
        /// Horizontal delta.
        dx: i16,
        /// Vertical delta.
        dy: i16,
    },
}

impl MessageEnvelope {
    /// Serializes the envelope.
    ///
    /// # Errors
    /// Returns [`CoreError::FrameSize`] if the encoding exceeds
    /// `MAX_CONTROL_FRAME_BYTES`, and [`CoreError::Malformed`] if `postcard`
    /// cannot encode the value.
    pub fn encode(&self) -> Result<Vec<u8>> {
        let bytes = postcard::to_allocvec(self).map_err(|_| CoreError::Malformed)?;
        if bytes.is_empty() || bytes.len() > MAX_CONTROL_FRAME_BYTES {
            return Err(CoreError::FrameSize { size: bytes.len() });
        }
        Ok(bytes)
    }

    /// Deserializes an envelope from an already length-checked frame.
    ///
    /// # Errors
    /// Returns [`CoreError::FrameSize`] if `bytes` is empty or longer than
    /// `MAX_CONTROL_FRAME_BYTES`, and [`CoreError::Malformed`] on any decoding
    /// failure. The size check happens before `postcard` touches the input
    /// (§9.1: allocation-DoS protection).
    pub fn decode(bytes: &[u8]) -> Result<Self> {
        if bytes.is_empty() || bytes.len() > MAX_CONTROL_FRAME_BYTES {
            return Err(CoreError::FrameSize { size: bytes.len() });
        }
        // `postcard::from_bytes` stops at the end of the value and ignores
        // whatever follows. A frame is length-prefixed, so trailing bytes mean
        // the two sides disagree about what the frame contains; that is a
        // malformed frame, not a decodable one with padding. Rejecting it also
        // keeps the encoding canonical, which the interop vectors of §17.2 rely
        // on.
        let (envelope, rest) =
            postcard::take_from_bytes::<Self>(bytes).map_err(|_| CoreError::Malformed)?;
        if !rest.is_empty() {
            return Err(CoreError::Malformed);
        }
        envelope.check_limits()?;
        Ok(envelope)
    }

    /// Enforces the per-message limits of §14 that are narrower than the
    /// frame bound (§9.1 allocation-DoS protection at the type level).
    ///
    /// # Errors
    /// [`CoreError::Malformed`] when any payload exceeds its constant:
    /// chat text over `CHAT_MAX_BYTES`, clipboard over `CLIPBOARD_MAX_BYTES`,
    /// a cursor whose pixel count contradicts its geometry or exceeds
    /// `MAX_CURSOR_SHAPE_PIXELS`, more than `MAX_MONITORS_PER_HOST` monitors,
    /// or a `FileOffer` larger than `FILE_OFFER_MAX_BYTES`.
    fn check_limits(&self) -> Result<()> {
        match &self.kind {
            MessageKind::Chat { text } => {
                if text.len() > CHAT_MAX_BYTES {
                    return Err(CoreError::Malformed);
                }
            }
            MessageKind::ClipboardSync { data } => {
                if data.len() > CLIPBOARD_MAX_BYTES {
                    return Err(CoreError::Malformed);
                }
            }
            MessageKind::CursorShape { shape } => {
                let pixels = usize::from(shape.width) * usize::from(shape.height);
                if pixels == 0 || pixels > MAX_CURSOR_SHAPE_PIXELS || shape.rgba.len() != pixels * 4
                {
                    return Err(CoreError::Malformed);
                }
                if usize::from(shape.hotspot_x) >= usize::from(shape.width)
                    || usize::from(shape.hotspot_y) >= usize::from(shape.height)
                {
                    return Err(CoreError::Malformed);
                }
            }
            MessageKind::MonitorsList { monitors } => {
                if monitors.len() > MAX_MONITORS_PER_HOST {
                    return Err(CoreError::Malformed);
                }
                for monitor in monitors {
                    if monitor.width == 0 || monitor.height == 0 {
                        return Err(CoreError::Malformed);
                    }
                }
            }
            MessageKind::FileOffer { size, .. } if *size > FILE_OFFER_MAX_BYTES => {
                return Err(CoreError::Malformed);
            }
            _ => {}
        }
        Ok(())
    }
}

/// Checks that `remote_major` matches [`PROTOCOL_MAJOR`].
///
/// # Errors
/// Returns [`CoreError::IncompatibleVersion`] on mismatch; the caller closes
/// the connection before any consent decision (§9.1, §18).
pub const fn check_version(remote_major: u16) -> Result<()> {
    if remote_major == PROTOCOL_MAJOR {
        Ok(())
    } else {
        Err(CoreError::IncompatibleVersion {
            local: PROTOCOL_MAJOR,
            remote: remote_major,
        })
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;
    use crate::constants::{
        AUDIO_CHANNELS, AUDIO_SAMPLE_RATE_HZ, CLIPBOARD_MAX_BYTES, FILE_OFFER_MAX_BYTES,
    };

    fn envelope(kind: MessageKind) -> MessageEnvelope {
        MessageEnvelope {
            session_id: [7u8; 16],
            direction: Direction::GuestToHost,
            seq: 0,
            kind,
            body: Vec::new(),
        }
    }

    #[test]
    fn roundtrip_preserves_envelope() {
        let original = envelope(MessageKind::ConsentGrant(Role::ViewOnly));
        let bytes = original.encode().unwrap();
        assert_eq!(MessageEnvelope::decode(&bytes).unwrap(), original);
    }

    #[test]
    fn empty_frame_is_rejected() {
        assert!(matches!(
            MessageEnvelope::decode(&[]),
            Err(CoreError::FrameSize { size: 0 })
        ));
    }

    #[test]
    fn trailing_bytes_make_a_frame_malformed() {
        let envelope = MessageEnvelope {
            session_id: [1u8; 16],
            direction: Direction::HostToGuest,
            seq: 0,
            kind: MessageKind::ConsentRevoke,
            body: Vec::new(),
        };
        let mut bytes = envelope.encode().unwrap();
        assert_eq!(MessageEnvelope::decode(&bytes).unwrap(), envelope);
        bytes.push(0xff);
        assert!(matches!(
            MessageEnvelope::decode(&bytes),
            Err(CoreError::Malformed)
        ));
    }

    #[test]
    fn oversized_frame_is_rejected_before_decoding() {
        let oversized = vec![0u8; MAX_CONTROL_FRAME_BYTES + 1];
        assert!(matches!(
            MessageEnvelope::decode(&oversized),
            Err(CoreError::FrameSize { .. })
        ));
    }

    #[test]
    fn major_mismatch_is_incompatible() {
        assert!(check_version(PROTOCOL_MAJOR).is_ok());
        assert!(matches!(
            check_version(PROTOCOL_MAJOR + 1),
            Err(CoreError::IncompatibleVersion { .. })
        ));
    }

    #[test]
    fn chat_roundtrips_and_oversize_is_rejected() {
        let long = "x".repeat(CHAT_MAX_BYTES);
        let original = envelope(MessageKind::Chat { text: long });
        let bytes = original.encode().unwrap();
        assert_eq!(MessageEnvelope::decode(&bytes).unwrap(), original);

        // One byte over the chat limit is a limit violation, not a crash.
        let mut oversized_text = String::with_capacity(CHAT_MAX_BYTES + 1);
        for _ in 0..=(CHAT_MAX_BYTES) {
            oversized_text.push('y');
        }
        let oversized = envelope(MessageKind::Chat {
            text: oversized_text,
        });
        assert!(matches!(
            MessageEnvelope::decode(&oversized.encode().unwrap()),
            Err(CoreError::Malformed)
        ));
    }

    #[test]
    fn keyframe_request_roundtrips() {
        let original = envelope(MessageKind::KeyframeRequest);
        let bytes = original.encode().unwrap();
        assert_eq!(MessageEnvelope::decode(&bytes).unwrap(), original);
    }

    #[test]
    fn cursor_shape_roundtrips_and_bad_geometry_is_rejected() {
        let shape = CursorShapeData {
            width: 2,
            height: 2,
            hotspot_x: 1,
            hotspot_y: 1,
            rgba: vec![0xAA; 2 * 2 * 4],
        };
        let original = envelope(MessageKind::CursorShape {
            shape: shape.clone(),
        });
        let bytes = original.encode().unwrap();
        assert_eq!(MessageEnvelope::decode(&bytes).unwrap(), original);

        // Pixel count disagreeing with the geometry is malformed, never a
        // short read further down the pipeline.
        let mut lying = shape;
        lying.rgba.pop();
        let bad = envelope(MessageKind::CursorShape { shape: lying });
        assert!(matches!(
            MessageEnvelope::decode(&bad.encode().unwrap()),
            Err(CoreError::Malformed)
        ));
    }

    #[test]
    fn monitors_list_roundtrips_and_overflow_is_rejected() {
        let monitors = vec![MonitorInfo {
            id: 0,
            width: 1920,
            height: 1080,
            primary: true,
        }];
        let original = envelope(MessageKind::MonitorsList {
            monitors: monitors.clone(),
        });
        let bytes = original.encode().unwrap();
        assert_eq!(MessageEnvelope::decode(&bytes).unwrap(), original);

        let flood = vec![
            MonitorInfo {
                id: 0,
                width: 1,
                height: 1,
                primary: false,
            };
            MAX_MONITORS_PER_HOST + 1
        ];
        let overflow = envelope(MessageKind::MonitorsList { monitors: flood });
        assert!(matches!(
            MessageEnvelope::decode(&overflow.encode().unwrap()),
            Err(CoreError::Malformed)
        ));
    }

    #[test]
    fn privacy_audio_and_file_abort_roundtrip() {
        let cases = [
            MessageKind::PrivacyMode { enabled: true },
            MessageKind::PrivacyModeAck { active: false },
            MessageKind::AudioStart {
                sample_rate_hz: AUDIO_SAMPLE_RATE_HZ,
                channels: AUDIO_CHANNELS,
            },
            MessageKind::AudioStop,
            MessageKind::FileAbort { transfer_id: 7 },
            MessageKind::FileChunkAck {
                transfer_id: 7,
                offset: 4096,
            },
        ];
        for kind in cases {
            let original = envelope(kind);
            let bytes = original.encode().unwrap();
            assert_eq!(MessageEnvelope::decode(&bytes).unwrap(), original);
        }
    }

    #[test]
    fn legacy_clipboard_limit_is_enforced_on_decode() {
        // The frame bound of §9.1 already keeps a >64 KiB clipboard off the
        // wire entirely: `encode` refuses before anything is sent.
        let oversized = envelope(MessageKind::ClipboardSync {
            data: vec![0; CLIPBOARD_MAX_BYTES + 1],
        });
        assert!(matches!(
            oversized.encode(),
            Err(CoreError::FrameSize { .. })
        ));
    }

    #[test]
    fn legacy_file_offer_size_limit_is_enforced_on_decode() {
        let oversized = envelope(MessageKind::FileOffer {
            name: "big.bin".to_owned(),
            size: FILE_OFFER_MAX_BYTES + 1,
            hash: [0; 32],
        });
        assert!(matches!(
            MessageEnvelope::decode(&oversized.encode().unwrap()),
            Err(CoreError::Malformed)
        ));
    }
}
